import type { AgentRole } from '@agentcity/types'

// Tools available to each role. Mapped to Composio action names.
export const ROLE_TOOLS: Record<AgentRole, string[]> = {
  EXEC_ASSISTANT: [
    'GMAIL_LIST_THREADS',
    'GMAIL_GET_THREAD',
    'GMAIL_CREATE_DRAFT',
    'GMAIL_SEND_EMAIL',
    'GOOGLECALENDAR_LIST_EVENTS',
    'GOOGLECALENDAR_CREATE_EVENT',
  ],
  RESEARCH_ANALYST: [
    'SERPAPI_SEARCH',
    'BROWSERBASE_SCRAPE_URL',
  ],
  CONTENT_WRITER: [
    'SERPAPI_SEARCH',
    'TWITTER_CREATE_TWEET',
    'LINKEDIN_CREATE_POST',
    'INSTAGRAM_CREATE_MEDIA_PUBLISH',
    'FACEBOOK_CREATE_POST',
    'YOUTUBE_UPLOAD_VIDEO',
    'TIKTOK_UPLOAD_VIDEO',
    'THREADS_CREATE_POST',
    'PINTEREST_CREATE_PIN',
  ],
  SALES_PROSPECTOR: [
    'SERPAPI_SEARCH',
    'BROWSERBASE_SCRAPE_URL',
  ],
  OPS_COORDINATOR: [
    'GOOGLECALENDAR_LIST_EVENTS',
    'GOOGLECALENDAR_CREATE_EVENT',
  ],
  FINANCIAL_ANALYST: [
    'SERPAPI_SEARCH',
    'BROWSERBASE_SCRAPE_URL',
  ],
  HR_MANAGER: [
    'GMAIL_LIST_THREADS',
    'GMAIL_GET_THREAD',
    'GMAIL_CREATE_DRAFT',
    'GMAIL_SEND_EMAIL',
    'GOOGLECALENDAR_LIST_EVENTS',
    'GOOGLECALENDAR_CREATE_EVENT',
  ],
  CUSTOMER_SUPPORT: [
    'GMAIL_LIST_THREADS',
    'GMAIL_GET_THREAD',
    'GMAIL_CREATE_DRAFT',
    'GMAIL_SEND_EMAIL',
  ],
  DATA_ANALYST: [
    'SERPAPI_SEARCH',
    'BROWSERBASE_SCRAPE_URL',
  ],
  MARKETING_STRATEGIST: [
    'SERPAPI_SEARCH',
    'BROWSERBASE_SCRAPE_URL',
    'TWITTER_CREATE_TWEET',
    'LINKEDIN_CREATE_POST',
    'INSTAGRAM_CREATE_MEDIA_PUBLISH',
    'FACEBOOK_CREATE_POST',
    'YOUTUBE_UPLOAD_VIDEO',
    'TIKTOK_UPLOAD_VIDEO',
    'THREADS_CREATE_POST',
    'PINTEREST_CREATE_PIN',
  ],
}

// These tools trigger the human-in-the-loop approval gate before execution
export const DESTRUCTIVE_TOOLS = new Set([
  'GMAIL_SEND_EMAIL',
  'GOOGLECALENDAR_CREATE_EVENT',
  'GOOGLECALENDAR_DELETE_EVENT',
  'GOOGLECALENDAR_UPDATE_EVENT',
  'TWITTER_CREATE_TWEET',
  'LINKEDIN_CREATE_POST',
  'INSTAGRAM_CREATE_MEDIA_PUBLISH',
  'FACEBOOK_CREATE_POST',
  'YOUTUBE_UPLOAD_VIDEO',
  'TIKTOK_UPLOAD_VIDEO',
  'THREADS_CREATE_POST',
  'PINTEREST_CREATE_PIN',
])

export function requiresApproval(toolName: string): boolean {
  return DESTRUCTIVE_TOOLS.has(toolName)
}
